RABBITMQ_USERNAME = "wsdot"
RABBITMQ_PASSWORD = "12sd3"
RABBITMQ_HOST = "localhost"
RABBITMQ_PORT = 5672
RABBIT_QUEUE_NAME = "ams"
RABBIT_EXCHANGE_NAME = "ams"
RABBIT_ROUTING_KEY = "ams"

RABBIT_QUEUE_MAX_SIZE = 400


MONGODB_URL ="asdfdsgger3454335fdgert3"
DATABASE_NAME = "mydatabase"